### PR TITLE
Updates installer to print info on Bash Completion

### PR DESCRIPTION
**Pull request by dom96**
Refs https://github.com/wasp-lang/wasp/issues/256

### CODE REVIEW

**Comment by dom96** [comment]
Gentle ping for review and merge (or at least a hacktoberfest-accept tag :))

**Comment by Martinsos** [comment]
Thanks @dom96 !

This is a very close, but I would suggest instead putting it after the rest of the output. RIght now, it is in the middle of instructions for creating a new app, while it is not needed to create a new app. Even though you marked it with optional, it still doesn't help with creating a new app.

So I would instead just have smth like this:
```
Wasp has been successfully installed! To create your first app, do:
- Add wasp to your PATH as described above.
- wasp new MyApp

Additionally, you can install bash completion for `wasp` by running `wasp completion` and following the instructions.
```

**Comment by dom96** [comment]
Makes sense. Done!

**Comment by Martinsos** [comment]
@dom96 LGTM, merged! Thanks!

**Pull request merged**
